[package]
name = "bitfrost"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
bendy = "0.3"
thiserror = "2.0.16"
sha1 = "0.10.6"
rand = "0.9.2"
urlencoding = "2.1.3"
reqwest = "0.12.23"
hex = "0.4.3"
bip_bencode = "0.4.4"
fs = "0.0.5"
